# Generated by Django 3.0.3 on 2020-02-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_orders',
            name='t_and_m',
        ),
    ]
