# Generated by Django 3.0.3 on 2020-02-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0002_remove_change_orders_t_and_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_orders',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='cop_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='ewt_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='gc_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='job_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='t_and_m',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='waiting_for_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='work_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='change_orders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
